require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 2.7
  Severity: error

  Exclude:
    - "bin/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Bundler/DuplicatedGem:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 100

Lint/ScriptPermission:
  Exclude:
    - "Rakefile"

Metrics/AbcSize:
  Max: 15
  Exclude:
    - "spec/**/*"
    - "db/migrate/*.rb"

Metrics/BlockLength:
  Max: 25
  Exclude:
    - "spec/**/*_spec.rb"
    - "spec/factories/*.rb"
    - "db/migrate/*.rb"
    - "config/environments/*.rb"
    - "config/routes.rb"

Metrics/ClassLength:
  Max: 100

Metrics/MethodLength:
  Max: 10
  Exclude:
    - "db/migrate/**/*.rb"

Rails/FilePath:
  EnforcedStyle: arguments

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  IgnoredMethods: [
    "to",
    "to_not",
    "require",
    "require_relative",
    "describe",
    "it",
    "context",
    "exit",
    "validate_presence_of",
    "belong_to",
    "have_many",
    "raise",
    "puts",
    "desc",
    "redirect_to",
    "render"
  ]
  Enabled: true
  Exclude:
    - "db/migrate/*.rb"
    - "Gemfile"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets
